import PetAdoptionPostConfirm from "@/components/shared/pet-adoption-post-confirm"
import { fetchAdoptedPetOwner, fetchPetAdoptionPostById, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"
import React from "react"

export const metadata = {
    title: "Xác nhận trao/nhận thú cưng",
    description: "Generated by Next.js",
}

const ConfirmPetAdoptionPost = async ({ params }: { params: { postId: string } }) => {
    const postId = params.postId

    const [postDetail, user, adoptedPetOwner] = await Promise.all([
        fetchPetAdoptionPostById({ postId }),
        fetchUser(),
        fetchAdoptedPetOwner({ postId }),
    ])

    if (!user) {
        redirect("/login")
    }

    if (!postDetail) {
        redirect("/find-pet")
    }

    if (!adoptedPetOwner) {
        redirect(`/pet-adoption/${postId}`)
    }
    // Chỉ có người đăng hoặc người được nhận pet mới có thể truy cập, nếu không thì redirect
    if (
        !(
            user._id.toString() === postDetail.poster._id.toString() ||
            user._id.toString() === adoptedPetOwner._id.toString()
        )
    ) {
        redirect(`/pet-adoption/${postId}`)
    }
    return (
        <PetAdoptionPostConfirm post={postDetail} user={user} adoptedPetOwner={adoptedPetOwner} />
    )
}

export default ConfirmPetAdoptionPost
