import ListReportAdmin from "@/components/shared/list-report-admin"
import { fetchReport, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"
import React from "react"

export const metadata = {
    title: "Quản lý hệ thống Pet Paradise",
    description: "Generated by Next.js",
}

const ManageReport = async () => {
    const [user, reports] = await Promise.all([fetchUser(), fetchReport()])

    if (!user) {
        redirect("/login")
    }

    if (user.role !== "admin") {
        redirect("/")
    }

    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex flex-col pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Quản lý báo cáo</div>
                        <div>Quản lý các báo cáo vi phạm do người dùng gửi</div>
                    </div>
                    {reports === null || reports.length === 0 ? (
                        <div className="w-full h-full flex items-center justify-center text-brown-1">
                            Hiện tại không có báo cáo nào
                        </div>
                    ) : (
                        // <ListPostAdmin posts={posts} user={user} />
                        <ListReportAdmin reports={reports} user={user} />
                    )}
                </div>
            </div>
        </div>
    )
}

export default ManageReport
