import TopBarPeople from "@/components/layout/top-bar-people"
import UserCard from "@/components/shared/user-card"
import { fetchOtherUser, fetchUser } from "@/lib/fetch"
import { IUserDocument } from "@/types"
import Image from "next/image"
import { redirect } from "next/navigation"

export const metadata = {
    title: "People",
    description: "Generated by Next.js",
}

const People = async () => {
    // const otherPeople = await fetchOtherUser()
    const [user, otherPeople] = await Promise.all([fetchUser(), fetchOtherUser()])

    if (!user) {
        redirect("/login")
    }

    return (
        <>
            {otherPeople === null ? (
                <div className="w-full h-full flex items-center justify-center">
                    There are no more users
                </div>
            ) : (
                <div className="flex flex-col gap-8">
                    {otherPeople.map((people: IUserDocument) => (
                        <UserCard key={people._id} people={people} user={user} />
                    ))}
                </div>
            )}
        </>
    )
}

export default People
