import ListOtherPeople from "@/components/shared/list-other-people"
import { fetchOtherUser, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Người dùng trên PetParadise",
    description: "Generated by Next.js",
}

const People = async () => {
    // const otherPeople = await fetchOtherUser()
    const [user, otherPeople] = await Promise.all([fetchUser(), fetchOtherUser()])

    if (!user) {
        redirect("/login")
    }

    return (
        <>
            {otherPeople === null ? (
                <div className="w-full h-full flex items-center justify-center">
                    Hiện tại không có người dùng nào khác
                </div>
            ) : (
                <ListOtherPeople user={user} otherPeople={otherPeople} />
            )}
        </>
    )
}

export default People
