import ItemCard from "@/components/shared/item-card"
import MenuShop from "@/components/shared/menu-shop"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { fetchUser } from "@/lib/fetch"
import { Loader2, Search, ShoppingCart } from "lucide-react"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Store",
    description: "Generated by Next.js",
}

const Store = async () => {
    const [user] = await Promise.all([fetchUser()])

    if (!user) {
        redirect(`/login`)
    }

    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Cửa hàng thú cưng</div>
                    </div>
                    <div className="flex justify-between">
                        <div className="relative border-brown-1 border-2 p-3 pr-10 rounded-2xl">
                            <input
                                type="text"
                                placeholder="Tìm kiếm sản phẩm ..."
                                className="focus:outline-none text-sm"
                            />
                            <Search className="absolute right-3 top-3 text-brown-1 hover:cursor-pointer transition-all hover:-translate-y-1.5" />
                        </div>
                        <div className="flex gap-3 items-center">
                            <div className="border-2 border-brown-1 p-3 flex gap-2 rounded-2xl text-brown-1 hover:cursor-pointer items-center">
                                <ShoppingCart className="transition-all hover:-translate-y-1.5" />
                                <div className="text-xs">{`(0)`}</div>
                            </div>
                            <DropdownMenu>
                                <DropdownMenuTrigger className="focus:outline-none">
                                    <Avatar className="hover:cursor-pointer">
                                        <AvatarImage
                                            src={user.profileImage || "/assets/images/avatar.jpeg"}
                                            alt="@avatar"
                                        />
                                        <AvatarFallback>
                                            <Loader2 className="w-5 h-5 animate-spin" />
                                        </AvatarFallback>
                                    </Avatar>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent>
                                    <DropdownMenuItem>Tạo sản phẩm</DropdownMenuItem>
                                    <DropdownMenuItem>Quản lý sản phẩm</DropdownMenuItem>
                                    <DropdownMenuItem>Quản lý đơn hàng</DropdownMenuItem>
                                </DropdownMenuContent>
                            </DropdownMenu>
                        </div>
                    </div>
                    <MenuShop />
                    <div className="grid grid-cols-2 max-md:grid-cols-1 gap-4 mt-8">
                        <ItemCard />
                        <ItemCard />
                        <ItemCard />
                        <ItemCard />
                        <ItemCard />
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Store
