import PostFeed from "@/components/shared/post-feed"
import { fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Liked Post",
    description: "Generated by Next.js",
}

const LikedPost = async () => {
    const user = await fetchUser()

    if (!user) {
        redirect("/login")
    }

    return (
        <>
            <div className="text-3xl font-semibold text-brown-1">Liked Post</div>
            {user.likedPosts.reverse().map((post) => (
                <div key={post._id}>
                    <PostFeed user={user} post={post} />
                </div>
            ))}
        </>
    )
}

export default LikedPost
