import PostDetailContainer from "@/components/container/post-detail-container"

export const metadata = {
    title: "Detail Post",
    description: "Generated by Next.js",
}

const DetailPost = ({ params }: { params: { postId: string } }) => {
    const postId = params.postId
    return <PostDetailContainer postId={postId} />
}

export default DetailPost
