import ProductDetail from "@/components/shared/product-detail"
import { fetchProductById, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Detail Product",
    description: "Generated by Next.js",
}

const DetailProduct = async ({ params }: { params: { productId: string } }) => {
    const { productId } = params
    const [product, user] = await Promise.all([fetchProductById({ productId }), fetchUser()])

    if (!product) {
        redirect("/store")
    }

    if (!user) {
        redirect(`/login`)
    }

    return <ProductDetail product={product} userByFetch={user} />
}

export default DetailProduct
