import ProductDetail from "@/components/shared/product-detail"
import { fetchProductById } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Detail Product",
    description: "Generated by Next.js",
}

const DetailProduct = async ({ params }: { params: { productId: string } }) => {
    const { productId } = params
    const product = await fetchProductById({ productId })

    if (!product) {
        redirect("/store")
    }

    return <ProductDetail product={product} />
}

export default DetailProduct
