import PetAdoptionPostDetail from "@/components/shared/pet-adoption-post-detail"
import { fetchPetAdoptionPostById, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Pet Adoption",
    description: "Generated by Next.js",
}

const DatailPetAdoptionPost = async ({ params }: { params: { postId: string } }) => {
    const postId = params.postId

    const [postDetail, user] = await Promise.all([
        fetchPetAdoptionPostById({ postId }),
        fetchUser(),
    ])

    if (!user) {
        redirect("/login")
    }

    if (!postDetail) {
        redirect("/find-pet")
    }

    return <PetAdoptionPostDetail post={postDetail} user={user} />
}

export default DatailPetAdoptionPost
