import ListOtherUserBySearch from "@/components/shared/list-other-people-by-search"
import { fetchSearchPeople, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Tìm kiếm người dùng",
    description: "Generated by Next.js",
}

const SearchPeople = async ({ params }: { params: { search: string } }) => {
    const user = await fetchUser()

    if (!user) {
        redirect("/login")
    }
    if (!params.search) {
        redirect("/")
    }

    const searchedPeople = await fetchSearchPeople({ search: decodeURI(params.search) })
    const listPeopleWithOutUser = searchedPeople?.filter(
        (people) => people._id.toString() !== user._id.toString(),
    )

    return (
        <>
            <div>
                {!listPeopleWithOutUser || listPeopleWithOutUser.length === 0 ? (
                    <div className="w-full h-full items-center justify-center flex text-brown-1">
                        There are no user according to your search request
                    </div>
                ) : (
                    <ListOtherUserBySearch
                        user={user}
                        listPeopleWithOutUser={listPeopleWithOutUser}
                        param={params.search}
                    />
                )}
            </div>
        </>
    )
}

export default SearchPeople
