import UserCard from "@/components/shared/user-card"
import { fetchUser } from "@/lib/fetch"
import { IUserDocument } from "@/types"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Search People",
    description: "Generated by Next.js",
}

const SearchPeople = async ({ params }: { params: { search: string } }) => {
    const user = await fetchUser()

    if (!user) {
        redirect("/login")
    }
    if (!params.search) {
        redirect("/")
    }

    return (
        <>
            test
            {/* {otherPeople === null ? (
                <div className="w-full h-full flex items-center justify-center">
                    There are no more users
                </div>
            ) : (
                <div className="flex flex-col gap-8">
                    {otherPeople.map((people: IUserDocument) => (
                        <UserCard key={people._id} people={people} user={user} />
                    ))}
                </div>
            )} */}
        </>
    )
}

export default SearchPeople
