import ChangePassword from "@/components/shared/change-password"
import UserInfo from "@/components/shared/user-info"
import UserInfoSkeleton from "@/components/skeleton/user-info-skeleton"
import { Suspense } from "react"

export const metadata = {
    title: "Profile",
    description: "Generated by Next.js",
}

const Profile = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex flex-col pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Manage Account</div>
                        <div>Manage your account information</div>
                    </div>
                    <Suspense fallback={<UserInfoSkeleton />}>
                        <UserInfo />
                    </Suspense>
                    <ChangePassword />
                </div>
            </div>
        </div>
    )
}

export default Profile
