import ChangePassword from "@/components/shared/change-password"
import Image from "next/image"

export const metadata = {
    title: "Profile",
    description: "Generated by Next.js",
}

const Profile = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex flex-col pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Manage Account</div>
                        <div>Manage your account information</div>
                    </div>
                    <div className="flex flex-col">
                        <div className="border-b py-2 border-brown-1 font-semibold text-2xl text-brown-1">
                            Profile
                        </div>
                        <div className="flex justify-between items-center p-5">
                            <Image
                                src={"/assets/images/avatar.jpeg"}
                                className="rounded-full"
                                alt="@shadcn"
                                width={140}
                                height={140}
                            />
                            <div className="flex flex-col gap-3 text-brown-1">
                                <div className="flex gap-2">
                                    <Image
                                        src={"/assets/images/circle-user-round.svg"}
                                        alt="user-round"
                                        width={25}
                                        height={25}
                                    />
                                    <div>@trieunguyentm</div>
                                </div>
                                <div className="flex gap-2">
                                    <Image
                                        src={"/assets/images/cake.svg"}
                                        alt="cake"
                                        width={25}
                                        height={25}
                                    />
                                    <div>2002-11-24</div>
                                </div>
                                <div className="flex gap-2">
                                    <Image
                                        src={"/assets/images/map-pin.svg"}
                                        alt="map-pin"
                                        width={25}
                                        height={25}
                                    />
                                    <div>Ha Noi</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ChangePassword />
                </div>
            </div>
        </div>
    )
}

export default Profile
