import UserInfoContainer from "@/components/container/user-info-container"
import ChangePasswordSkeleton from "@/components/skeleton/change-password-skeleton"
import UserInfoSkeleton from "@/components/skeleton/user-info-skeleton"
import { Suspense } from "react"

export const metadata = {
    title: "Trang cá nhân",
    description: "Generated by Next.js",
}

const Profile = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex flex-col pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Quản lý tài khoản</div>
                        <div>Quản lý tài khoản và thông tin cá nhân</div>
                    </div>
                    <Suspense
                        fallback={
                            <>
                                <UserInfoSkeleton />
                                <ChangePasswordSkeleton />
                            </>
                        }
                    >
                        <UserInfoContainer />
                    </Suspense>
                </div>
            </div>
        </div>
    )
}

export default Profile
