import MessageListUser from "@/components/shared/message-list-user"
import { fetchOtherUser } from "@/lib/fetch"

export const metadata = {
    title: "Message",
    description: "Generated by Next.js",
}

const Message = async () => {
    const otherUser = await fetchOtherUser()

    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll gap-10">
                    {/* TITLE */}
                    <div className="text-brown-1 font-semibold">
                        Select the friends you want to start a conversation with
                    </div>
                    {/* SEARCH CONTACT */}
                    <MessageListUser otherUser={otherUser} />
                </div>
            </div>
        </div>
    )
}

export default Message
