import MessageContainer from "@/components/container/message-container"
import { fetchOtherUser, fetchUser } from "@/lib/fetch"
import Image from "next/image"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Message",
    description: "Generated by Next.js",
}

const Message = async () => {
    const otherUser = await fetchOtherUser()

    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll gap-10">
                    {/* TITLE */}
                    <div className="text-brown-1 font-semibold">
                        Select the friends you want to start a conversation with
                    </div>
                    {/* SEARCH CONTACT */}
                    <div className="w-full border rounded-md px-2 py-3 relative">
                        <input
                            type="text"
                            className="w-full py-3 pl-2 pr-8 focus:outline-none bg-transparent"
                            placeholder="Search contact ..."
                        />
                        <Image
                            src={"/assets/images/search.svg"}
                            alt="search"
                            width={25}
                            height={25}
                            className="absolute top-6 right-2 cursor-pointer"
                        />
                    </div>
                    <MessageContainer otherUser={otherUser} />
                </div>
            </div>
        </div>
    )
}

export default Message
