import MessageListUser from "@/components/shared/message-list-user"
import TitleMessagePage from "@/components/shared/title-message-page"
import { fetchChatByUser, fetchOtherUser, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Tin nhắn",
    description: "Generated by Next.js",
}

const Message = async () => {
    const [chats, user, otherUser] = await Promise.all([
        fetchChatByUser(),
        fetchUser(),
        fetchOtherUser(),
    ])

    if (!user) {
        redirect("/login")
    }

    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll gap-10">
                    {/* TITLE */}
                    <TitleMessagePage chats={chats} user={user} />

                    {/* SEARCH CONTACT */}
                    <MessageListUser otherUser={otherUser} />
                </div>
            </div>
        </div>
    )
}

export default Message
