import PostFeedDetail from "@/components/shared/post-feed-detail"
import { fetchSearchPost, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Tìm kiếm bài viết",
    description: "Generated by Next.js",
}

const SearchPost = async ({ params }: { params: { search: string } }) => {
    const user = await fetchUser()

    if (!user) {
        redirect("/login")
    }
    if (!params.search) {
        redirect("/")
    }

    const searchedPosts = await fetchSearchPost({ search: decodeURI(params.search) })

    return (
        <div>
            {!searchedPosts || searchedPosts.length === 0 ? (
                <div className="w-full h-full items-center justify-center flex text-brown-1">
                    Không có bài đăng nào được tìm thấy
                </div>
            ) : (
                <div className="flex flex-col gap-10">
                    {searchedPosts.reverse().map((post) => (
                        <div key={post._id}>
                            <PostFeedDetail user={user} post={post} />
                        </div>
                    ))}
                </div>
            )}
        </div>
    )
}

export default SearchPost
