import FormCreatePost from "@/components/form/form-create-post"

export const metadata = {
    title: "Create Post",
    description: "Generated by Next.js",
}

const CreatePost = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <FormCreatePost />
            </div>
        </div>
    )
}

export default CreatePost
