import EditProductContainer from "@/components/container/edit-product-container"
import { fetchProductById, fetchUser } from "@/lib/fetch"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Edit Product",
    description: "Generated by Next.js",
}

const EditProductPage = async ({ params }: { params: { productId: string } }) => {
    const { productId } = params
    const [user, product] = await Promise.all([fetchUser(), fetchProductById({ productId })])

    if (!product) {
        redirect("/store")
    }

    if (!user) {
        redirect(`/login`)
    }

    if (user._id.toString() !== product.seller._id.toString()) {
        redirect(`/store/product-detail/${product._id.toString()}`)
    }

    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex flex-col pb-2 text-brown-1 transition-all hover:-translate-x-2">
                        <Link href={`/store/product-detail/${product._id.toString()}`}>
                            <ArrowLeft />
                        </Link>
                    </div>
                    <div className="flex pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Chỉnh sửa thông tin sản phẩm</div>
                    </div>
                    <EditProductContainer product={product} />
                </div>
            </div>
        </div>
    )
}

export default EditProductPage
