import PostFeedDetail from "@/components/shared/post-feed-detail"
import { fetchDetailPost, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Bài viết trên PetParadise",
    description: "Generated by Next.js",
}

const DetailPost = async ({ params }: { params: { postId: string } }) => {
    const { postId } = params

    const [user, post] = await Promise.all([fetchUser(), fetchDetailPost({ postId })])

    if (!user) {
        redirect("/login")
    }

    if (!post) {
        redirect("/")
    }

    return <PostFeedDetail post={post} user={user} />
}

export default DetailPost
