import MessageDetailContainer from "@/components/container/message-detail-container"
import { fetchDetailChat, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"
import React from "react"

export const metadata = {
    title: "Message",
    description: "Generated by Next.js",
}

const DetailMessagePage = async ({ params }: { params: { chatId: string } }) => {
    const chatId = params.chatId
    const [chatDetail, user] = await Promise.all([fetchDetailChat({ chatId }), fetchUser()])

    if (!user) {
        redirect("/login")
    }

    if (!chatDetail) {
        redirect("/message")
    }

    return <MessageDetailContainer chatDetail={chatDetail} user={user} />
}

export default DetailMessagePage
