import FilterFindPet from "@/components/shared/filter-find-pet"

export const metadata = {
    title: "Find Pet",
    description: "Generated by Next.js",
}

const FindPet = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <div className="bg-white rounded-xl w-full p-5 flex flex-col max-h-[100vh] overflow-scroll">
                    <div className="flex pb-16 text-brown-1">
                        <div className="font-semibold text-3xl">Find Pet</div>
                    </div>
                    <FilterFindPet />
                </div>
            </div>
        </div>
    )
}

export default FindPet
