import FormCreatePostAdoptionPet from "@/components/form/form-create-post-adoption-pet"

export const metadata = {
    title: "Tạo bài đăng tìm người nhận nuôi thú cưng",
    description: "Generated by Next.js",
}

const CreatePetAdoptionPost = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <FormCreatePostAdoptionPet />
            </div>
        </div>
    )
}

export default CreatePetAdoptionPost
