import PostContainer from "@/components/container/post-container"

export const metadata = {
    title: "Home Page",
    description: "Generated by Next.js",
}

const HomePage = () => {
    return (
        <>
            <div className="text-3xl font-semibold text-brown-1">Feed</div>
            <PostContainer />
        </>
    )
}

export default HomePage
