import FormCreatePostFindPet from "@/components/form/form-create-post-find-pet"

export const metadata = {
    title: "Create Post Find Pet",
    description: "Generated by Next.js",
}

const CreatePostFindPet = () => {
    return (
        <div className="px-5 py-3">
            <div className="flex h-[calc(100vh-24px)] bg-pink-1 rounded-xl p-5 w-full">
                <FormCreatePostFindPet />
            </div>
        </div>
    )
}

export default CreatePostFindPet
