import PetAdoptionRequestDetail from "@/components/shared/list-pet-adoption-request"
import { fetchAdoptionRequestByPost, fetchUser } from "@/lib/fetch"
import { redirect } from "next/navigation"

export const metadata = {
    title: "Yêu cầu nhận nuôi thú cưng",
    description: "Generated by Next.js",
}

const RequestPetAdoption = async ({ params }: { params: { postId: string } }) => {
    const postId = params.postId

    const [user, dataRequest] = await Promise.all([
        fetchUser(),
        fetchAdoptionRequestByPost({ postId }),
    ])

    if (!user) {
        redirect("/login")
    }

    if (!dataRequest) {
        redirect(`/pet-adoption/${postId}`)
    }

    return <PetAdoptionRequestDetail postId={postId} dataRequest={dataRequest} user={user} />
}

export default RequestPetAdoption
